### ISSUE TITLE
Some feedback on your post

### ISSUE THREAD

**Issue by stephmarx** [CariWest/cariwest.github.io#3]
I really empathize with this blog entry of yours. Somehow, this week was made me feel even more vulnerable too and my blog entry was a bit tough to write. I also feel like my insecurities are making it difficult to recognize my strengths and I wanted you to know that, at the very least, you're not alone. :grinning: 

Also, I like how you separated your values into different spheres of your life and gave yourself an affirmation for each, I might have to go back and add that to mine! It seems like you have a good sense of how you can help yourself succeed.

I also wanted to say something about your mention that you "can be OCD." I suppose I wanted to mention that you should consider: do you have obsessive compulsive disorder or do you just value order and are detail oriented? If you do have OCD: Much love, this is tough. If you don't have OCD: It can be difficult for people with mental disorders to see their disorders trivialized in everyday use. OCD means a lot more than just valuing order and being detail oriented; it's an incredibly difficult thing to live with and involves extreme and irrational behaviors. This was such a tiny part of your blog post, but I wanted to mention my concern as this is something that's pretty important to me. Thanks for taking the time to read this, please don't let it get you down. :relaxed:

**Comment by CariWest** [comment]
I am sorry that I touched on such a sensitive subject in such an insensitive way! I have never been tested for or diagnosed with OCD. However, I've had the term used negatively in describing my actions in the past. I'll adjust my post to be more accurate to my actual feelings. Thank you for the feedback!
